services:

  mysql-database:
    image: mysql-copy
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "mypassword"
    ports:
      - "3306:3306"


  redis-cache:
    hostname: redis
    container_name: "redis"
    image: redis
    ports:
    - "6379:6379"