services:

  #app:
   # container_name: SpringBootAppTest
    #build:
     # dockerfile: Dockerfile
    #ports:
     # - "8080:8080"
    #depends_on:
     # - mysql-database
      #- redis-cache
      #- rabbitmq


  mysql-database:
    image: mysql
    container_name: "mysql-compose"
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "mypassword"
    ports:
      - "3306:3306"


  redis-cache:
    restart: always
    container_name: "redis-compose"
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq-compose"
    ports:
      - "5672:5672"
      - "15672:15672"

#environment:
  #- API_KEY=