spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379


  rabbitmq:
    host: localhost
    port: 5672

  queues:
    product-service: product-service.queue
    image-service: image-service.queue

  keys:
    product-service: product-service.key
    image-service: image-service.key

  direct-exchange:
    name: exchange




